host: 'localhost'
port: 3306
username: 'Cubix'
password: 'CubixTMPlanet2019'
database: 'cubixbase'

ranks:
  player:
    id: player
    rankToString: 'Player'
    rankColor: GRAY
    colorChat: GRAY
    perms:
      - 'coins.fetch'
      - 'credits.fetch'
      - 'servers.switch'
    default: true
  vip:
    id: vip
    rankToString: 'VIP'
    rankColor: YELLOW
    colorChat: WHITE
    perms:
      - 'cow.disguise'
      - 'joinquit.message'
      - 'fly.hub'
    inherit:
      - player
  vip+:
    id: vip+
    rankToString: 'VIP+'
    rankColor: GOLD
    colorChat: WHITE
    perms:
      - 'enderman.disguise'
      - 'joinquit.message'
      - 'fly.hub'
    inherit:
      - vip
  youtuber:
    id: youtuber
    rankToString: 'Youtuber'
    rankColor: GOLD
    colorChat: WHITE
    perms:
      - 'nick.use'
      - 'joinquit.message'
      - 'fly.hub'
    inherit:
      - vip+
  friend:
    id: friend
    rankToString: 'Friend'
    rankColor: WHITE
    colorChat: WHITE
    perms:
      - 'staff.chat'
      - 'joinquit.message'
      - 'fly.hub'
    inherit:
      - vip+
  partner:
    id: partner
    rankToString: 'Partner'
    rankColor: GOLD
    colorChat: WHITE
    perms:
      - 'partner.use'
      - 'fly.hub'
    inherit:
      - player
  builder:
    id: builder
    rankToString: 'Builder'
    rankColor: DARK_GREEN
    colorChat: WHITE
    perms:
      - 'build.use'
      - 'joinquit.message'
      - 'fly.hub'
      - 'queues.bypass'
    inherit:
      - vip+
  helper:
    id: helper
    rankToString: 'Helper'
    rankColor: AQUA
    colorChat: WHITE
    perms:
      - 'mute.use'
      - 'kick.use'
      - 'joinquit.message'
      - 'fly.hub'
      - 'queues.bypass'
    inherit:
      - player
  moderator:
    id: moderator
    rankToString: 'Moderator'
    rankColor: DARK_AQUA
    colorChat: WHITE
    perms:
      - 'ban.use'
    inherit:
      - helper
  resp_mod:
    id: resp_mod
    rankToString: 'Resp. Moderation'
    rankColor: RED
    colorChat: WHITE
    perms:
      - 'block.staff.use'
    inherit:
      - moderator
  developer:
    id: developer
    rankToString: 'Developer'
    rankColor: BLUE
    colorChat: WHITE
    perms:
      - '*'
  admin:
    id: admin
    rankToString: 'Admin'
    rankColor: RED
    colorChat: RED
    perms:
      - '*'