host: 'localhost'
port: 3306
username: ''
password: ''
database: ''

ranks:
  none:
    id: none
    rankToString: 'None'
    rankColor: GRAY
    colorChat: GRAY
    perms:
      - ''
  player:
    id: player
    rankToString: 'Player'
    rankColor: GRAY
    colorChat: GRAY
    perms:
      - 'coins.fetch'
      - 'credits.fetch'
      - 'servers.switch'
    default: true
  vip:
    id: vip
    rankToString: 'VIP'
    rankColor: YELLOW
    colorChat: WHITE
    perms:
      - 'cow.disguise'
    inherit:
      - player
  vip+:
    id: vip+
    rankToString: 'VIP+'
    rankColor: GOLD
    colorChat: WHITE
    perms:
      - 'enderman.disguise'
    inherit:
      - vip
  youtuber:
    id: youtuber
    rankToString: 'Youtuber'
    rankColor: GOLD
    colorChat: WHITE
    perms:
      - 'nick.use'
    inherit:
      - vip+
  friend:
    id: friend
    rankToString: 'Friend'
    rankColor: WHITE
    colorChat: WHITE
    perms:
      - 'staff.chat'
    inherit:
      - vip+
  partner:
    id: partner
    rankToString: 'Partner'
    rankColor: GOLD
    colorChat: WHITE
    perms:
      - 'partner.use'
    inherit:
      - player
  builder:
    id: builder
    rankToString: 'Builder'
    rankColor: DARK_GREEN
    colorChat: WHITE
    perms:
      - 'build.use'
    inherit:
      - vip+
  helper:
    id: helper
    rankToString: 'Helper'
    rankColor: AQUA
    colorChat: WHITE
    perms:
      - 'mute.use'
      - 'kick.use'
      - 'tp.use'
    inherit:
      - player
  moderator:
    id: moderator
    rankToString: 'Moderator'
    rankColor: DARK_AQUA
    colorChat: WHITE
    perms:
      - 'ban.use'
      - 'tp.use'
    inherit:
      - helper
  resp_mod:
    id: resp_mod
    rankToString: 'Resp. Modération'
    rankColor: RED
    colorChat: WHITE
    perms:
      - 'block.staff.use'
    inherit:
      - moderator
  developer:
    id: developer
    rankToString: 'Developer'
    rankColor: BLUE
    colorChat: WHITE
    perms:
      - '*'
  admin:
    id: admin
    rankToString: 'Admin'
    rankColor: RED
    colorChat: RED
    perms:
      - '*'