host: 'localhost'
port: 3306
username: 'Cubix'
password: 'CubixTMPlanet2019'
database: 'cubixbase'

ranks:
  player:
    id: player
    colorChat: GRAY
    rankToString: '§7Player'
    perms:
      - 'coins.fetch'
      - 'credits.fetch'
      - 'servers.switch'
    default: true
  vip:
    id: vip
    rankToString: '§eVIP'
    colorChat: WHITE
    perms:
      - 'cow.disguise'
    inherit:
      - player
  vip+:
    id: vip+
    rankToString: '§6VIP+'
    colorChat: WHITE
    perms:
      - 'enderman.disguise'
    inherit:
      - vip
  youtuber:
    id: youtuber
    rankToString: '§6Youtuber'
    colorChat: WHITE
    perms:
      - 'nick.use'
    inherit:
      - vip+
  friend:
    id: friend
    rankToString: '§fFriend'
    colorChat: WHITE
    perms:
      - 'staff.chat'
    inherit:
      - vip+
  partner:
    id: partner
    rankToString: '§6Partner'
    colorChat: WHITE
    perms:
      - 'partner.use'
    inherit:
      - player
  builder:
    id: builder
    rankToString: '§2Builder'
    colorChat: WHITE
    perms:
      - 'build.use'
    inherit:
      - vip+
  helper:
    id: helper
    rankToString: '§bHelper'
    colorChat: WHITE
    perms:
      - 'mute.use'
      - 'kick.use'
    inherit:
      - player
  moderator:
    id: moderator
    rankToString: '§3Moderator'
    colorChat: WHITE
    perms:
      - 'ban.use'
    inherit:
      - helper
  resp_mod:
    id: resp_mod
    rankToString: '§cResp. Modération'
    colorChat: WHITE
    perms:
      - 'block.staff.use'
    inherit:
      - moderator
  developer:
    id: developer
    rankToString: '§9Developer'
    colorChat: WHITE
    perms:
      - '*'
  admin:
    id: admin
    rankToString: '§cAdmin'
    colorChat: RED
    perms:
      - '*'