data:
  host: localhost
  port: 3306
  username: ''
  password: ''
  database: ''

ranks:
  player:
    id: player
    rankToString: Player
    rankColor: GRAY
    colorChat: GRAY
    perms:
    - coins.fetch
    - credits.fetch
    - servers.switch
    default: true
  vip:
    id: vip
    rankToString: VIP
    rankColor: YELLOW
    colorChat: WHITE
    perms:
    - cow.disguise
    - rank.messagesyntax
    - joinquit.message
    inherit:
    - player
  vip+:
    id: vip+
    rankToString: VIP+
    rankColor: GOLD
    colorChat: WHITE
    perms:
    - enderman.disguise
    inherit:
    - vip
  youtuber:
    id: youtuber
    rankToString: Youtuber
    rankColor: GOLD
    colorChat: WHITE
    perms:
    - nick.use
    inherit:
    - vip+
  friend:
    id: friend
    rankToString: Friend
    rankColor: WHITE
    colorChat: WHITE
    perms:
    - staff.chat
    - rank.messagesyntax
    - joinquit.message
    inherit:
    - player
  partner:
    id: partner
    rankToString: Partner
    rankColor: GOLD
    colorChat: WHITE
    perms:
    - partner.use
    - rank.messagesyntax
    - joinquit.message
    inherit:
    - player
  builder:
    id: builder
    rankToString: Builder
    rankColor: DARK_GREEN
    colorChat: WHITE
    perms:
    - build.use
    - rank.messagesyntax
    - joinquit.message
    inherit:
    - player
  helper:
    id: helper
    rankToString: Helper
    rankColor: AQUA
    colorChat: WHITE
    perms:
    - mute.use
    - kick.use
    - rank.messagesyntax
    - joinquit.message
    inherit:
    - player
  moderator:
    id: moderator
    rankToString: Moderator
    rankColor: DARK_AQUA
    colorChat: WHITE
    perms:
    - ban.use
    - rank.messagesyntax
    - joinquit.message
    inherit:
    - helper
  resp_mod:
    id: resp_mod
    rankToString: Resp. Modération
    rankColor: RED
    colorChat: WHITE
    perms:
    - block.staff.use
    inherit:
    - moderator
  developer:
    id: developer
    rankToString: Developer
    rankColor: BLUE
    colorChat: WHITE
    perms:
    - '*'
  admin:
    id: admin
    rankToString: Admin
    rankColor: RED
    colorChat: RED
    perms:
    - '*'
