main: com.cubixmc.CubixAPI
name: CubixAPI
version: 1.0.1
author: [Eliviel, ZelphixSama, Pipo]
commands:
  coins:
    description: Gestion de coins.
  credits:
  ban:
    description: Ban permanently.
  unban:
    description: Unban un joueur.
  rank:
    description: Rank management.
  tempban:
    description: Temporarily ban.
  mute:
    description: Mute a player.
  unmute:
    description: Unmute a player.
  tempmute:
    description: Tempmute a player.