main: eu.cubixmc.com.CubixAPI
name: CubixAPI
version: 1.0
author: Eliviel
commands:
  coins:
    description: Gestion de coins.
  credits:
  ban:
    description: Bannir definitivement.
  unban:
    description: Unban un joueur.
  rank:
    description: Gestion des ranks.
  tempban:
    description: Bannir temporairement.
  mute:
    description: Mute a player.
  unmute:
    description: Unmute a player.
  tempmute:
    description: Tempmute a player.